version: 2.0

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 53
  scheduled-workflow:
    triggers:
      - schedule:
          cron: " 12 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
jobs:
  build:
    steps:
      - checkout
      # Bundle install dependencies
      - run: echo Test