version: 2.0

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "23 14 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Bundle install dependencies1
      - run: echo Build1
  build2:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Bundle install dependencies
      - run: echo Build2