# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: anujagarwal30594
          password: Whitelotus123@  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      - run:      
          name: Find current working directory
          command: pwd
      - run:
          name: Installing chromedriver and assigning permissions to launch
          command: sudo apt-get install unzip | wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/2.11/chromedriver_linux64.zip && sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
      - run:          
          name: Find list of contents
          command: ls
      - run:          
          name: Install npm pakages
          command:  npm install --save-dev nightwatch-api nightwatch cucumber chromedriver cucumber-pretty
      - run:          
          name: Execute tests
          command:  npm run e2e-test
